osx_image: xcode9
language: objective-c
podfile: Example/Podfile
bundler_args: "--without development --deployment"
cache:
  - bundler
  - cocoapods
script:
- set -o pipefail && xcodebuild -workspace Example/loudspeaker.xcworkspace -scheme Tests -configuration Debug clean build test -sdk iphonesimulator -destination platform="iOS Simulator,OS=latest,name=iPhone X" | xcpretty -c
